language: node_js
node_js:
  - "6"

addons:
  google-chrome: latest

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- "npm start &"

script: 
- "karma start karma.conf.js --single-run"
- "PORT=8081 mocha test/server"
- "nightwatch"